apiVersion: v1
kind: Service
metadata:
  namespace: fordong-domain
  name: service-fordong-domain
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: app-fordong-domain
